spring:
  main:
    web-application-type: reactive
  application:
    name: study-gateway
  cloud:
    gateway:
      routes:
        - id: user-role-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**, /api/roles/**
          filters:
            - JwtAuthenticationFilter
#  datasource:
#    url: jdbc:mysql://localhost:3306/platformDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: myuser1
#    password: mA3leDa9#8*dfk
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 20      # 커넥션 풀 최대 크기 (HikariCP 기본 풀러 사용)
#      minimum-idle: 5
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      validation-timeout: 5000
#      pool-name: MyHikariCP
#      auto-commit: true
#  jpa:
#    hibernate:
#      ddl-auto: update           # 개발: update/ 운영: validate 또는 none
#    show-sql: true              # 디버깅 시 true, 운영에서는 false 권장
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect # 버전에 맞는 Dialect 지정
#    open-in-view: false    # OSIV 반드시 false
#  cloud:
#    openfeign:
#      client:
#        config:
#          default:
#            connectTimeout: 3000
#            readTimeout: 5000
#            loggerLevel: full # 운영: BASIC/ERROR
##            decode404: false

server.port: 9000

logging:
  level: 
    root: DEBUG # feignclient FULL 로그를 보려면 DEBUG