spring:
  main:
    web-application-type: reactive
  application:
    name: study-gateway
  cloud:
    gateway:
      routes:
        - id: user-role-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**, /api/roles/**
          filters:
            - JwtAuthenticationFilter

server.port: 9000

logging:
  level: 
    root: DEBUG # feignclient FULL 로그를 보려면 DEBUG