spring:
  main:
    web-application-type: reactive
  application:
    name: study-gateway
  cloud:
    gateway:
      routes:
        - id: user-role-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**, /api/roles/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: userRoleCircuitBreaker
                fallbackUri: forward:/fallback/userRoleFallback
                statusCodes:
                  - 500
                  - NOT_FOUND
  autoconfigure: # circuitBreaker 가 spring security 요소를 자동으로 불러와 제거
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
server.port: 9000

logging:
  level: 
    root: DEBUG # feignclient FULL 로그를 보려면 DEBUG